### ISSUE TITLE
Background location

### ISSUE THREAD

**Issue by stairs1** [stairs1/memory-expansion-tools#14]

**Comment by CaydenPierce** [comment]
done already
see email

**Comment by CaydenPierce** [comment]
done in rfe branch

**Comment by stairs1** [comment]
No this is a separate issue: need extra perms to keep tracking location on
android while app is in background.

**Comment by stairs1** [comment]
Put it up there so you aren't wondering why not all the phrases are sending
location

**Comment by CaydenPierce** [comment]
ack

**Comment by stairs1** [comment]
Will address this evening
