### ISSUE TITLE
Android Notifies of Mic activation

### ISSUE THREAD

**Issue by JamesPierce82** [stairs1/memory-expansion-tools#20]
Not sure if there is a fix for this, but on my Google Pixel 2 every time the mix is turned on to record, and off to process the last statement my phone makes a noise to inform me the mic is being used. While useful, I find it to be distracting. If there was a way to even just turn off the "mic is turning off" noise, it would be less disruptive to the flow of recording for me.

**Comment by CaydenPierce** [comment]
I looked around and this is unsupported by the api. Hacking around it by trying to mute before and unmute after the voice rec beep proves annoying for the user and not working well. I always mute when the app is on. What I did was mute the mic on voice rec starting, but just not unmute

**Comment by JamesPierce82** [comment]
Alright. I figured that might be the case. I'll start doing the same.
