### ISSUE TITLE
User Login is Case Sensitive

### ISSUE THREAD

**Issue by JamesPierce82** [stairs1/memory-expansion-tools#23]
This can either be a bug or a feature. If it is intended, it should be stated somewhere on each login page so the user knows.

I discovered this on Android, where my keyboard has a bad habit of capitalizing the first letter in username fields. I created my login on desktop, and did not capitalize the letter when creating the account.

**Comment by CaydenPierce** [comment]
If it is unclear, then we should say it, sure. I added this user case-sensitivity heads-up on the web side.
