### ISSUE TITLE
funny timestamps with incorrect minutes

### ISSUE THREAD

**Issue by kylemath** [stairs1/memory-expansion-tools#26]
on the website only I think
<img width="231" alt="Screen Shot 2020-03-29 at 3 14 50 PM" src="https://user-images.githubusercontent.com/3662613/77861086-c70a6800-71c7-11ea-9c48-42d6a0538d9b.png">

**Comment by CaydenPierce** [comment]
Thanks. Fixed this on develop branch. Will merge this fix in when we finish and merge the dashboard + tagging system.
